### ISSUE TITLE
Complete restructure of sections

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#261]
We need to restructure all sections of the website for a better user-friendly experience and more immediate informations. I would suggest a totally re-style with modern visualizations.

## To-do list
- [x] Homepage needs a complete re-style;
- [x] Rules section is ok but needs some adjustments;
- [x] "Chi siamo" section rework;
- [x] Groups section needs to be totally reworked;
- [x] Extra groups needs to be merged in groups section;
- [x] Services section re-work;

## Related issue:
Representatives section is useless right now (#251);

**Comment by Giuseppetm** [comment]
@MarcoBuster you can share your doubts about ui here.

**Comment by Giuseppetm** [comment]
# Homepage structure

![image](https://user-images.githubusercontent.com/52317197/131910758-f802cafe-6364-4bb2-ab42-4b65f518e47a.png)

This is just a scratch, then I add all the other info on the actual homepage.
