### ISSUE TITLE
Restructure of services section

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#326]
## Todo:
- [x] Pivot to select services category
- [x] URL parameter for #servicetype 
- [x] Restructure actual data
