### ISSUE TITLE
Styles management overhaul

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#343]
### Todo list
- [ ] Maybe use styled components?
- [ ] Re-organize breakpoints with variables and sm,md etc. behaviours ([example here](https://github.com/Giuseppetm/prometheus-portfolio/blob/main/src/Styles/Responsive.scss)), set based on bootstrap ones;
- [ ] Delete old styles not longer needed;
- [x] #381;
- [ ] Modularize something if needed.
