### ISSUE TITLE
New flex behaviour for website structure

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#381]
Right now the website has a pretty bad external structure.
If we have sections with not a lot of content the footer must stay on the bottom of the screen in a smart way.

## Todo list
- [x] Apply this to body content:
```css
min-height: 100vh;
display: flex;
flex-direction: column;
```
- [x] `flex-grow:1` to section element
- [x] remove `position: absolute` and `margin-bottoms` to body

## Expected result
![image](https://user-images.githubusercontent.com/52317197/216622295-91c08077-8279-4f1a-affb-ed69ffc0eddc.png)
![image](https://user-images.githubusercontent.com/52317197/216622337-51028305-5a17-44a3-91f3-a0e236467e08.png)
