### ISSUE TITLE
Performance and SEO overhaul

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#384]
- [x] #379
- [x] #400 
- [x] #352
- [x] #387 
- [x] Font swap on fonts usage;
- [ ] Check all the pages of the website for potential improvements in SEO and performance;
- [ ] https://nextjs.org/docs/pages/building-your-application/deploying/production-checklist#caching

### SEO
- [x] Add h1, h2 etc. where needed;
- [x] Add alt property to images.
